apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: wordpress
  name: wordpress
  namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wordpress
    spec:
      containers:
      - image: acrcnspdevweuqrld7.azurecr.io/wordpress:latest
        name: wordpress
        resources: {}
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql-cnsp-dev-weu.mysql.database.azure.com
        - name: WORDPRESS_DB_USER
          value: mysqladmin
        - name: WORDPRESS_DB_PASSWORD
          value: ABC123!@#  
        - name: WORDPRESS_DB_NAME
          value: wordpress
        - name: WORDPRESS_CONFIG_EXTRA
          value: |
            define('MYSQL_CLIENT_FLAGS', MYSQLI_CLIENT_SSL);
        volumeMounts:
        - mountPath: /var/www/html/wordpress
          name: wp-persistent-storage
      volumes: 
      - name: wp-persistent-storage
        persistentVolumeClaim:
        claimName: wordpress-pvc
status: {}